[project]
name = "zerobus-databricks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "faker>=40.1.2",
    "fastapi[standard]>=0.128.0",
    "pandas>=3.0.0",
    "requests>=2.32.5",
    "uvicorn>=0.40.0",
]
